### ISSUE TITLE
/bin/sh: fastANI: command not found

### ISSUE THREAD

**Issue by emmannaemeka** [moshi4/ANIclustermap#10]
Hi,
I am trying to run this tool and encountered this error

# Step1: Run fastani between all-vs-all 41 genomes.
/bin/sh: fastANI: command not found
Traceback (most recent call last):
  File "/Users/emmannaemeka/mambaforge/bin/ANIclustermap", line 8, in <module>
    sys.exit(main())
  File "/Users/emmannaemeka/mambaforge/lib/python3.9/site-packages/aniclustermap/aniclustermap.py", line 29, in main
    run(**args.__dict__)
  File "/Users/emmannaemeka/mambaforge/lib/python3.9/site-packages/aniclustermap/aniclustermap.py", line 75, in run
    ani_df = parse_ani_matrix(ani_matrix_file)
  File "/Users/emmannaemeka/mambaforge/lib/python3.9/site-packages/aniclustermap/aniclustermap.py", line 229, in parse_ani_matrix
    with open(matrix_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'anicluster_map/work/fastani_result.matrix'

**Comment by moshi4** [comment]
Hi @emmannaemeka,

An error has occurred because fastANI has not been successfully installed in your environment.
Please make sure fastANI is installed in your environment and then try running ANIclustermap.

This issue has the same error content as #4, so looking at #4 may also be helpful in resolving this issue.
