### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by NantiaL** [moshi4/ANIclustermap#11]
Hey, after long time of running the tool without problems, when running ANIclustermap I encountered now the following issue: 

```
# Step1: Run fastani between all-vs-all 13 genomes.
dyld: Library not loaded: @rpath/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/leonidou/opt/anaconda3/envs/ANIclustermap/bin/fastANI
  Reason: image not found
Traceback (most recent call last):
  File "/Users/leonidou/opt/anaconda3/envs/ANIclustermap/bin/ANIclustermap", line 10, in <module>
    sys.exit(main())
  File "/Users/leonidou/opt/anaconda3/envs/ANIclustermap/lib/python3.8/site-packages/aniclustermap/aniclustermap.py", line 29, in main
    run(**args.__dict__)
  File "/Users/leonidou/opt/anaconda3/envs/ANIclustermap/lib/python3.8/site-packages/aniclustermap/aniclustermap.py", line 75, in run
    ani_df = parse_ani_matrix(ani_matrix_file)
  File "/Users/leonidou/opt/anaconda3/envs/ANIclustermap/lib/python3.8/site-packages/aniclustermap/aniclustermap.py", line 229, in parse_ani_matrix
    with open(matrix_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ANIclustermap_Results/work/fastani_result.matrix'
```

It must be something with the dyld library that I was not able to fix.
The tool worked so far perfectly for me, and suddenly I get this error..Thanks in advance!

**Comment by moshi4** [comment]
Are you getting the error with MacOS? I have never used MacOS so I honestly don't know why this error occurs.

I don't know if this will solve the problem, but try to recreate the conda environment and reinstall ANIclustermap.

**Comment by NantiaL** [comment]
It still doesn't work. I tried the installation in an older environment that I created for a different purpose and it worked.
