### ISSUE TITLE
--mode skani error

### ISSUE THREAD

**Issue by Juandemendieta** [moshi4/ANIclustermap#16]
Hello, good morning, I have the following error when I try to run skani mode:

```sh
sg24@plataforma2:~/ECL/Cepas/Unicycler$ ANIclustermap -i ./fasani -o skani2  --fig_width 30 --fig_height 30  --cmap_ranges 80,85,90,95,100 -m skani                                                                                        
# Step1: Run skani between all-vs-all 145 genomes.
/bin/sh: 1: skani: Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/ANIclustermap", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aniclustermap/aniclustermap.py", line 29, in main
    run(**args.__dict__)
  File "/usr/local/lib/python3.9/dist-packages/aniclustermap/aniclustermap.py", line 75, in run
    ani_df = parse_ani_matrix(ani_matrix_file)
  File "/usr/local/lib/python3.9/dist-packages/aniclustermap/aniclustermap.py", line 229, in parse_ani_matrix
    with open(matrix_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'skani2/work/skani_result.matrix'
```

could you help me?

**Comment by moshi4** [comment]
Try giving it execute permission with the command `chmod +x /path/to/skani`.

**Comment by SergeyBaikal** [comment]
Same problem.

**Comment by Juandemendieta** [comment]
> Same problem.

Hi Sergey, in my case I hadn't noticed but I didn't have Skani installed on our server, I don't know if this comment is useful to you.

**Comment by SergeyBaikal** [comment]
> > Same problem.
> 
> Hi Sergey, in my case I hadn't noticed but I didn't have Skani installed on our server, I don't know if this comment is useful to you.

Hi, [Juandemendieta](https://github.com/Juandemendieta)  Oh, that's really true. Thank you so much!
