### ISSUE TITLE
fastANI command not found

### ISSUE THREAD

**Issue by NantiaL** [moshi4/ANIclustermap#4]
Hey, when running ANIclustermap I encountered the following issues:

```
# Step1: Run fastANI between all-vs-all 7 genomes.
/bin/sh: fastANI: command not found
Traceback (most recent call last):
  File "/Users/leonidou/opt/anaconda3/bin/ANIclustermap", line 8, in <module>
    sys.exit(main())
  File "/Users/leonidou/opt/anaconda3/lib/python3.8/site-packages/aniclustermap/aniclustermap.py", line 44, in main
    run(
  File "/Users/leonidou/opt/anaconda3/lib/python3.8/site-packages/aniclustermap/aniclustermap.py", line 93, in run
    fastani_df = parse_fastani_matrix(fastani_matrix_file)
  File "/Users/leonidou/opt/anaconda3/lib/python3.8/site-packages/aniclustermap/aniclustermap.py", line 231, in parse_fastani_matrix
    with open(matrix_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Results/work/fastani_result.matrix'
```
Could you please help me how to resolve the issue? Many thanks in advance!

**Comment by moshi4** [comment]
> /bin/sh: fastANI: command not found

The above error message means that fastANI has not been successfully installed in your environment.

Did you install ANIclustermap with the following command? If so, fastANI should be installed together with it.

    conda install -c bioconda -c conda-forge aniclustermap

If ANIclustermap is installed with the above command and it does not work properly, please check if fastANI can be installed properly once with the following command.

    # Install fastANI
    conda install -c bioconda fastani
    # Check fastANI installation
    fastANI -h

**Comment by NantiaL** [comment]
Thank you very much! Now it works fine!
