### ISSUE TITLE
Genome number limitations?

### ISSUE THREAD

**Issue by vebaev** [moshi4/ANIclustermap#9]
Is there a genome number limit? When I run it with 20-30genomes is fine, but when I input >50 I got error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/ANIclustermap", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aniclustermap/aniclustermap.py", line 44, in main
    run(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aniclustermap/aniclustermap.py", line 93, in run
    fastani_df = parse_fastani_matrix(fastani_matrix_file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aniclustermap/aniclustermap.py", line 231, in parse_fastani_matrix
    with open(matrix_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pl_out2/work/fastani_result.matrix'
```

**Comment by moshi4** [comment]
Hi, @vebaev

ANIclustermap has no limit on the number of genomes as input.

Since you say it works fine with 20 ~ 30 genomes, it may be that the 50+ genome files you input contain something that FastANI cannot process properly. I cannot check your genome files, so I can only say this much.

**Comment by vebaev** [comment]
Hi, @moshi4 

can I contact you via email so I can privately share the genomes?

**Comment by moshi4** [comment]
Please send an email to `sy.41211_[at]_gmail.com`

**Comment by vebaev** [comment]
Thanks. I have sent an email.

**Comment by moshi4** [comment]
I ran ANIclustermap between your 207 genomes in my environment and it outputs results with no problems. Therefore, I think there is no problem with the input genome file.

Since I could not reproduce the error in my environment, it may be a bit difficult to identify/resolve the cause of the error...
